# Copyright (c) 2026 LATMOS (France, UMR 8190) and IGE (France, UMR 5001).
#
# License: BSD 3-clause "new" or "revised" license (BSD-3-Clause).
#
# Image providing a GNU/Linux WRF-infra ready environment.
#

FROM docker.io/library/debian:latest

RUN <<EOF

# Make the system a bit more friendly
echo 'PS1="\[\033[34m\]WRF-Chem-Polar\[\033[00m\] \[\033[35m\]\w\[\033[00m\]\n"' > /root/.bashrc
echo 'alias ls="ls --group-directories-first --color=auto"' >> /root/.bashrc
echo 'alias l="ls -lh --group-directories-first --color=auto"' >> /root/.bashrc
echo 'alias python="python3"' >> /root/.bashrc

# # Update system
apt-get -y update
apt-get -y upgrade

# Install basic dependencies
apt-get -y install \
    less \
    emacs-nox \
    vim \
    git \
    python3 \
    python3-pip

# Clone WRF-infra
mkdir /wrf
cd /wrf
git clone https://github.com/WRF-Chem-Polar/WRF-infra.git ./infra

# Install dependencies for WRF-infra
apt-get -y install \
    python3-pyproj \
    python3-netcdf4 \
    python3-xarray \
    python3-shapely \
    python3-cdsapi \
    python3-pandas \
    python3-scipy \
    python3-cartopy \
    python3-dask \
    nco \
    cdo

# Install dependencies for WRF and WRF-Chem
apt-get -y install \
    gfortran \
    libnetcdf-dev \
    libnetcdff-dev \
    bison \
    flex \
    openmpi-bin \
    libopenmpi-dev

EOF
