# Copyright (c) 2026 LATMOS (France, UMR 8190) and IGE (France, UMR 5001).
#
# License: BSD 3-clause "new" or "revised" license (BSD-3-Clause).
#
# Image providing a snakemake-enabled environment.
#
FROM docker.io/library/debian:latest
RUN <<EOF
apt-get -y update
apt-get -y upgrade
apt-get -y install snakemake
EOF
