--- Makefile	2026-09-28 09:50:24.990467790 +0200
+++ Makefile.new	2026-10-02 11:01:25.647674898 +0200
@@ -442,8 +442,6 @@
               \( ! -f noahmp/drivers/wrf/NoahmpIOVarInitMod.F90 \) -o \( ! -f noahmp/drivers/wrf/NoahmpIOVarType.F90 \) -o \
 	      \( ! -f noahmp/drivers/wrf/GroundWaterMmfMod.F90 \) -o \( ! -f noahmp/drivers/wrf/NoahmpUrbanDriverMainMod.F90 \) -o \
 	      \( ! -f noahmp/src/NoahmpMainMod.F90 \) -o \( ! -f noahmp/src/NoahmpVarType.F90 \) ] ; then \
-		echo Pulling in NoahMP submodule ; \
-		( cd .. ; git submodule update --init --recursive ) ; \
 		( cd ../run ; ln -sf ../phys/noahmp/parameters/NoahmpTable.TBL . ) ; \
 		( cd ../run ; ln -sf ../phys/noahmp/parameters/snicar_drdt_bst_fit_60_c070416.nc . ) ; \
 		( cd ../run ; ln -sf ../phys/noahmp/parameters/snicar_optics_480bnd_c012422.nc . ) ; \
@@ -451,16 +449,9 @@
 	else \
 		echo No action required for NoahMP submodule ; \
 	fi
-	@if [ \( ! -f phys/physics_mmm/README.md \) ] ; then \
-		echo Pulling in MMM-physics submodule ; \
-		( cd .. ; git submodule update --init --recursive ) ; \
-	else \
-		echo No action required for MMM-physics submodule ; \
-	fi
+	echo No action required for MMM-physics submodule ;
 	@if [ \( ! -f module_bl_mynnedmf.F \) -o \( ! -f module_bl_mynnedmf_common.F \) -o \
 	      \( ! -f module_bl_mynnedmf_driver.F \) ] ; then \
-	      	echo Pulling in MYNN-EDMF submodule ; \
-		( cd .. ; git submodule update --init --recursive ) ; \
 		ln -sf MYNN-EDMF/module_bl_mynnedmf.F90 module_bl_mynnedmf.F ; \
 		ln -sf MYNN-EDMF/WRF/module_bl_mynnedmf_common.F90 module_bl_mynnedmf_common.F ; \
 		ln -sf MYNN-EDMF/WRF/module_bl_mynnedmf_driver.F90 module_bl_mynnedmf_driver.F ; \
@@ -470,8 +461,6 @@
 	@if [ \( ! -f module_sf_mynnsfc_driver.F \) -o \( ! -f module_sf_mynnsfc_common.F \) -o \
 	      \( ! -f module_sf_mynnsfc_land.F \) -o \( ! -f module_sf_mynnsfc_water.F \) -o \
 	      \( ! -f module_sf_mynnsfc_ice.F \) ] ; then \
-		echo Pulling in MYNN-SFC submodule ; \
-		( cd .. ; git submodule update --init --recursive ) ; \
 		ln -sf MYNN-SFC/WRF/module_sf_mynnsfc_driver.F90 module_sf_mynnsfc_driver.F ; \
 		ln -sf MYNN-SFC/WRF/module_sf_mynnsfc_common.F90 module_sf_mynnsfc_common.F ; \
 		ln -sf MYNN-SFC/module_sf_mynnsfc_land.F90 module_sf_mynnsfc_land.F ; \
@@ -482,8 +471,6 @@
 	fi
 	@if [ \( ! -f module_cu_gfl_wrf.F \) -o \( ! -f module_cu_gfl_common.F \) -o \
 	      \( ! -f module_cu_gfl_deep.F \) -o \( ! -f module_cu_gfl_sh.F \) ] ; then \
-	      	echo Pulling in GFL submodule ; \
-		( cd .. ; git submodule update --init --recursive ) ; \
 		ln -sf GFL/module_cu_gfl_sh.F90  module_cu_gfl_sh.F; \
 		ln -sf GFL/module_cu_gfl_deep.F90  module_cu_gfl_deep.F; \
 		ln -sf GFL/WRF/module_cu_gfl_common.F90 module_cu_gfl_common.F ; \
@@ -495,8 +482,6 @@
 	      \( ! -f module_mp_tempo_cfgs.F90 \) -o \( ! -f module_mp_tempo_aerosols.F90 \) -o \
 	      \( ! -f module_mp_tempo_ml.F90 \) -o \( ! -f module_mp_tempo_diags.F90 \) -o \
               \( ! -f module_mp_tempo_utils.F90 \) -o \( ! -f module_mp_tempo_params.F90 \) ] ; then \
-                echo Pulling in TEMPO submodule ; \
-		( cd .. ; git submodule update --init --recursive ) ; \
 		ln -sf TEMPO/src/module_mp_tempo_cfgs.F90 module_mp_tempo_cfgs.F90 ; \
 		ln -sf TEMPO/src/module_mp_tempo_params.F90 module_mp_tempo_params.F90 ; \
 		ln -sf TEMPO/src/module_mp_tempo_utils.F90 module_mp_tempo_utils.F90 ; \
