--- Makefile	2026-05-27 14:19:08.000000000 +0200
+++ Makefile.new	2026-06-02 09:21:51.000000000 +0200
@@ -260,8 +260,6 @@
 submodules :
 	@if [ \( ! -f module_sf_noahmpdrv.F \) -o \( ! -f module_sf_noahmp_glacier.F \) -o \
 	      \( ! -f module_sf_noahmp_groundwater.F \) -o \( ! -f module_sf_noahmplsm.F \) ] ; then \
-		echo Pulling in NoahMP submodule ; \
-		( cd .. ; git submodule update --init --recursive ) ; \
 		ln -sf noahmp/drivers/wrf/module_sf_noahmpdrv.F . ; \
 		ln -sf noahmp/src/module_sf_noahmp_glacier.F . ; \
 		ln -sf noahmp/src/module_sf_noahmp_groundwater.F . ; \
